# Build script
environment:
  website_name: appychristmas
  website_psw:
    secure: AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA024zePPvCk66gydYIQs9yAAAAAACAAAAAAADZgAAwAAAABAAAAB+S5P1aJBIWhhkE+KiLdv0AAAAAASAAACgAAAAEAAAAJPtZ5ujVMi64DpIJh8lHv4YAAAApa0suOy34O14yJnlFRxU5MqVR8XtH/v6FAAAABr7QCyAlMkCTbyPuHaAtJgjl4w8

init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" -Configuration "Release"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/
    - netcore11
    
# Build cache
cache:
- tools -> build.cake

artifacts:
- path: artifacts
  name: appychristmas
 
deploy:
  - provider: WebDeploy
    server: https://appychristmasfork.scm.azurewebsites.net:443/msdeploy.axd?site=appychristmasfork
    website: appychristmasfork
    username: $appychristmasfork
    password:
      secure: 5Orq1J3LNhCmkcpwzVuHZqLo+uhgWt3NULq3Ezz2hRO/4OfLQ9mD/E5cbAo8ceHcJe8q64mBiymdw23SqWWu3g==
    remove_files: true
    app_offline: true
    artifact: appychristmas
  